variable "cidr_block" {}
variable "public_subnet_1_cidr" {}
variable "public_subnet_2_cidr" {}
variable "availability_zone_1" {}
variable "availability_zone_2" {}
variable "private_subnet_1_cidr" {}
variable "private_subnet_2_cidr" {}
variable "public_route_tbl_cidr_block" {}
variable "stage" {}
variable "organization" {}
variable "project_name" {}
